name: 11 - Working with Inputs

on: 
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Skip deployment and only print build output"
        type: boolean
        default: false
      target: 
        required: true
        type: environment
        description: "Which environment the workflow will target"
      tag:
        type: choice
          - v1
          - v2
          - v3
        default: v3
        description: "Release from which to build and deploy"


      
