name: 16 - Working with Environments

on:
  workflow_dispatch:
    
jobs:
  deploying-staging:
    runs-on: ubuntu-latest
    environment: staging
    env: 
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    steps:
      - name: Echo vars
        run: |
          echo "Deploying to staging"
  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploying-staging
    steps:
      - name: E2E tests
        run: echo " E2E test"
  deploying-prod:
    runs-on: ubuntu-latest
    needs: e2e-tests
    environment: prod
    env: 
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    steps:
      - name: Echo vars
        run: |
          echo "Deploying to prod"
    
